name: GamePeekrBackendBuildAndTest

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: Backend/GamePeekr

    - name: Build Projects
      run: dotnet build --no-restore
      working-directory: Backend/GamePeekr
    
  
  
  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Restore Dependencies
        run: dotnet restore
        working-directory: Backend/GamePeekr

      - name: Test Projects
        run:  dotnet test --settings test.runsetting
        working-directory: Backend/GamePeekr/GamePeekrTest

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2.10.0
        if: always()
        with:
          files: |
            Backend/GamePeekr/OwnTestResult/MyTestResults.xml
