name: GamePeekrBackendBuildAndTest

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

jobs:
  build:
      runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: ./Backend/GamePeekr

    - name: List Directory Contents
      run: ls -la ./Backend/GamePeekr

    - name: Build Projects
      run: |
        msbuild /p:Configuration=Release GamePeekr.sln
      working-directory: ./Backend/GamePeekr

    - name: Debug Info
      run: |
        pwd
        ls -la
