name: GamePeekrBackendBuildAndTest

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x

    - name: Restore Dependencies
      run: dotnet restore
      working-directory: Backend/GamePeekr

    - name: Build Projects
      run: dotnet build --no-restore
      working-directory: Backend/GamePeekr
    
    - name: Test Projects
      run: dotnet test --no-build --verbosity normal
      working-directory: Backend/GamePeekr
