name: GamePeekrBackendBuildAndTest

on:
  push:
    branches: [ "Development" ]
  pull_request:
    branches: [ "Development" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.202

    - name: Restore Dependencies
      run: dotnet restore

    - name: Debug Info
      run: |
        pwd
        ls -la

    - name: Build with MSBuild
      run: |
        msbuild /p:Configuration=Release ./Backend/GamePeekr/GamePeekr.sln
      working-directory: ./Backend/GamePeekr/GamePeekr
